### ISSUE TITLE
Не работает SPM

### ISSUE THREAD

**Issue by BugorBN** [usedesk/UseDeskSwift#11]
Исправления вносил [сюда](https://github.com/BugorBN/UseDeskSwift) и открыл #10

**Comment by Mr-Sergey-K** [comment]
Изменения добавлены в 2.4.0

**Comment by BugorBN** [comment]
<img width="1155" alt="Screenshot 2022-01-24 at 00 37 48" src="https://user-images.githubusercontent.com/56770320/150698946-c2731690-26ee-4cf1-bcc2-1bb0904b8f64.png">

а вы пробовали сами подключить useDesk через spm?
