### ISSUE TITLE
Неправильно работает knowledgeBaseID

### ISSUE THREAD

**Issue by 2Grey** [usedesk/UseDeskSwift#13]
Если при открытии UseDesk в параметр `knowledgeBaseID` передать _nil_, а не `""`, то откроется База знаний, а не чат поддержки.

Текущий код проверки поля (UseDeskSDK.swift:61):
```swift
if knowledgeBaseID != ""
```

Предлагаю заменить код на:
```swift
if let knowledgeBaseID = knowledgeBaseID, knowledgeBaseID.isEmpty == false
```

**Comment by DevITF** [comment]
Данный момент будет исправлен в версии 2.4.0

**Comment by Mr-Sergey-K** [comment]
Данный момент будет исправлен в 2.4.0
