### ISSUE TITLE
Не работает SPM, версия 2.4.2

### ISSUE THREAD

**Issue by BugorBN** [usedesk/UseDeskSwift#15]
<img width="1440" alt="Screenshot 2022-01-28 at 13 15 55" src="https://user-images.githubusercontent.com/56770320/151529390-0df4a1e4-8ed8-48ea-b5ad-7b2e20e9196f.png">

сложно подключить проект через SPM и сбилдить самостоятельно? 
Что за поддержка? уже третью версию не можете починить SPM

**Comment by Mr-Sergey-K** [comment]
Рабочая Верси доступна теперь в отдельном репозитории - https://github.com/usedesk/UseDeskSPM
