### ISSUE TITLE
DialogflowView crash

### ISSUE THREAD

**Issue by Ra1ONE1** [usedesk/UseDeskSwift#16]
**SDK version 2.4.4**

ErrorStatus: False init chat

Crashed: com.apple.main-thread
0  App                      0x595a8c closure #1 in DialogflowView.reloadHistory() + 147 (DialogflowView.swift:147)
1  App                      0xaf550 thunk for @escaping @callee_guaranteed () -> () + 4375983440 (<compiler-generated>:4375983440)
2  libdispatch.dylib              0x602b0 _dispatch_call_block_and_release + 24
3  libdispatch.dylib              0x61298 _dispatch_client_callout + 16
4  libdispatch.dylib              0xfce0 _dispatch_main_queue_callback_4CF$VARIANT$mp + 904
5  CoreFoundation                 0x9a298 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
6  CoreFoundation                 0x946f8 __CFRunLoopRun + 2528
7  CoreFoundation                 0x937d0 CFRunLoopRunSpecific + 572
8  GraphicsServices               0x3570 GSEventRunModal + 160
9  UIKitCore                      0xb302d0 -[UIApplication _run] + 1052
10 UIKitCore                      0xb3584c UIApplicationMain + 164
11 App                      0xaff0 main + 11 (main.m:11)
12 libdyld.dylib                  0x1140 start + 4

**Comment by Ra1ONE1** [comment]
На данный момент UseDesk генерит memory leaks 
Воспроизвести можно, открыв и закрыв Чат несколько раз
И предполагаю это и вызывает Cras
![Снимок экрана 2022-03-09 в 13 55 11](https://user-images.githubusercontent.com/100838026/157398347-58193e48-0a83-4a31-8bd3-fcdcfa82cb1c.png)
![Снимок экрана 2022-03-09 в 13 55 16](https://user-images.githubusercontent.com/100838026/157398360-5017fa5e-d4bb-4154-a03e-8da3a4cb5be9.png)
h

**Comment by Ra1ONE1** [comment]
**SDK version 3.0.0**
Crash amount increased dramatically

Crashed: com.apple.main-thread
0  App                      0x5d6494 closure #1 in DialogflowView.reloadHistory() + 133 (DialogflowView.swift:133)
1  App                      0x26c344 thunk for @escaping @callee_guaranteed () -> () + 4298900292 (<compiler-generated>:4298900292)
2  libdispatch.dylib              0x1e68 _dispatch_call_block_and_release + 32
3  libdispatch.dylib              0x3a2c _dispatch_client_callout + 20
4  libdispatch.dylib              0x11f48 _dispatch_main_queue_drain + 928
5  libdispatch.dylib              0x11b98 _dispatch_main_queue_callback_4CF + 44
6  CoreFoundation                 0x522f0 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 16
7  CoreFoundation                 0xc1f4 __CFRunLoopRun + 2532
8  CoreFoundation                 0x1f6b8 CFRunLoopRunSpecific + 600
9  GraphicsServices               0x1374 GSEventRunModal + 164
10 UIKitCore                      0x513e88 -[UIApplication _run] + 1100
11 UIKitCore                      0x2955ec UIApplicationMain + 364


**It appears when user inits chat**

**Comment by LeLuckyVint** [comment]
Проблема актуальна

**Comment by nichvolod** [comment]
Hi there! Sorry for keeping you without news. This issue is solved now
