### ISSUE TITLE
Краш при загрузке изображения

### ISSUE THREAD

**Issue by Sc4pego4t** [usedesk/UseDeskSwift#18]
<img width="854" alt="image" src="https://user-images.githubusercontent.com/37747001/186414361-c007da50-94b5-4c7c-9b84-3db4b0aa1cec.png">
<img width="873" alt="image" src="https://user-images.githubusercontent.com/37747001/186414403-1c25a03d-bc93-4850-8afc-4c66bea86260.png">

крашится метод на брекпоинте, кажется нужно это делать на главном потоке

**Comment by nichvolod** [comment]
Hi there! Sorry for keeping you without news. This issue is solved now
