### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by leitm** [usedesk/UseDeskSwift#19]
UseDesk version 3.4.1
Device iPhone 12 iOS 16.3.1
Crash appears when we trying to show chat modally. Content in chat should contain buttons and other visuals

libc++abi: terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Incorrect display node thread affinity - this method should not be called off the main thread after the ASDisplayNode's view or layer have been created'
terminating with uncaught exception of type NSException

-------------------
Crash in file UDTextMessageCellNode.swift  line 63
func setSell() {
....
 addSubnode(tableButtonsNode)

removing "self.tableButtonsNode.view.separatorStyle = .none" (line 61) fixes that crash 
-------------------

StackTrace:

* thread #6, queue = 'com.apple.root.user-initiated-qos', stop reason = signal SIGABRT
    frame #0: 0x00000002118bf674 libsystem_kernel.dylib`__pthread_kill + 8
    frame #1: 0x00000002220231ac libsystem_pthread.dylib`pthread_kill + 268
    frame #2: 0x00000001db420c8c libsystem_c.dylib`abort + 180
    frame #3: 0x0000000221f62b8c libc++abi.dylib`abort_message + 132
    frame #4: 0x0000000221f52a80 libc++abi.dylib`demangling_terminate_handler() + 336
    frame #5: 0x00000001ccf39d3c libobjc.A.dylib`_objc_terminate() + 144
    frame #6: 0x0000000221f61f28 libc++abi.dylib`std::__terminate(void (*)()) + 20
    frame #7: 0x0000000221f61ec4 libc++abi.dylib`std::terminate() + 56
    frame #8: 0x00000001ccf4fbec libobjc.A.dylib`objc_terminate + 16
    frame #9: 0x000000010ce52044 libdispatch.dylib`_dispatch_client_callout2 + 40
    frame #10: 0x000000010ce6a470 libdispatch.dylib`_dispatch_apply_invoke_and_wait + 236
    frame #11: 0x000000010ce695e8 libdispatch.dylib`_dispatch_apply_with_attr_f + 1288
    frame #12: 0x000000010ce69838 libdispatch.dylib`dispatch_apply + 108
  * frame #13: 0x000000010ab2939c AsyncDisplayKit`ASDispatchApply(iterationCount=2, queue=0x000000010ceb9440, threadCount=0, work=0x000000010ab1ad1c) at ASDispatch.mm:17:5
    frame #14: 0x000000010ab1ac38 AsyncDisplayKit`-[ASDataController _allocateNodesFromElements:strictlyOnCurrentThread:](self=0x0000000281130000, _cmd="_allocateNodesFromElements:strictlyOnCurrentThread:", elements=2 elements, strictlyOnCurrentThread=NO) at ASDataController.mm:185:7
    frame #15: 0x000000010ab202dc AsyncDisplayKit`__40-[ASDataController updateWithChangeSet:]_block_invoke.53(.block_descriptor=0x000000028032e030, strictlyOnCurrentThread=NO) at ASDataController.mm:658:7
    frame #16: 0x000000010ab203d0 AsyncDisplayKit`__40-[ASDataController updateWithChangeSet:]_block_invoke.54(.block_descriptor=0x000000028032d540) at ASDataController.mm:684:7
    frame #17: 0x000000010ce5053c libdispatch.dylib`_dispatch_call_block_and_release + 32
    frame #18: 0x000000010ce51ff0 libdispatch.dylib`_dispatch_client_callout + 20
    frame #19: 0x000000010ce5a25c libdispatch.dylib`_dispatch_lane_serial_drain + 1432
    frame #20: 0x000000010ce5adc8 libdispatch.dylib`_dispatch_lane_invoke + 420
    frame #21: 0x000000010ce67cac libdispatch.dylib`_dispatch_workloop_worker_thread + 740
    frame #22: 0x000000022201cdf8 libsystem_pthread.dylib`_pthread_wqthread + 288

**Comment by nichvolod** [comment]
Hi there! Thank you for reaching us. 

We have started investigation on this issue and will tell you as soon as we find something out ;)

**Comment by nichvolod** [comment]
Fixed: https://github.com/usedesk/UseDeskSwift/releases/tag/3.4.2
