### ISSUE TITLE
Error while demo project building

### ISSUE THREAD

**Issue by GipsySh** [usedesk/UseDeskSwift#20]
I've tried to build demo project according to [Launching a demo project](https://github.com/usedesk/UseDeskSwift#launching-a-demo-project) manual section, but I've got error `No such module ‘UseDesk_SDK_Swift’`

1. Copy source code into /UseDeskSwift-3.4.4
2. Start Terminal
3. Go to the Example folder of the cloned repository
`cd /UseDeskSwift-3.4.4/Example `
4. Execute command 
`pod install`

I’ve got the following command result (it seems it’s ok):

```
Analyzing dependencies
Downloading dependencies
Installing Alamofire (5.6.1)
Installing IQKeyboardManagerSwift (6.5.10)
Installing MarkdownKit (1.7.1)
Installing PINCache (3.0.3)
Installing PINOperation (1.2.1)
Installing PINRemoteImage (3.0.3)
Installing ReachabilitySwift (5.0.0)
Installing Socket.IO-Client-Swift (16.0.1)
Installing Starscream (4.0.4)
Installing SwiftSoup (2.4.3)
Installing Texture (3.1.0)
Installing UseDesk_SDK_Swift (3.4.4)
Generating Pods project
Integrating client project
Pod installation complete! There are 2 dependencies from the Podfile and 12 total pods installed.
```

5. Open /UseDeskSwift-3.4.4/Example/UseDesk.xcworkspace in Xcode
6. Select UseDesk_Example scheme and run the project

At this point I've got error `No such module ‘UseDesk_SDK_Swift’.`

I checked /UseDeskSwift-3.4.4/Example/Podfile and found `pod 'UseDesk_SDK_Swift', :path => '../'`
But there is no UseDesk_SDK_Swift in that path. Therefore I’ve replaced this line in Podfile with `pod 'UseDesk_SDK_Swift’.`
UseDesk_SDK_Swift appeared in installed dependencies when pods updating:

```
Update all pods
Updating local specs repositories
Analyzing dependencies
Downloading dependencies
Installing Alamofire 5.7.1 (was 5.6.1)
Installing IQKeyboardManagerSwift 6.5.11 (was 6.5.10)
Installing PINOperation 1.2.2 (was 1.2.1)
Installing SwiftSoup 2.6.0 (was 2.4.3)
Installing UseDesk_SDK_Swift (3.4.4)
Generating Pods project
Integrating client project
Pod installation complete! There are 2 dependencies from the Podfile and 12 total pods installed.
```

But the same error still occurred. 
It seems some default project settings are wrong, but I can’t found the reason. Can you help to solve the problem?

**Comment by nichvolod** [comment]
Hi there! 

You need to follow this steps:

1. Go to https://github.com/usedesk/UseDeskSwift
2. Press Code -> Download zip. Then you need to decompress archive on your local machine, go to "Example" folder and install Pods there

**Comment by GipsySh** [comment]
I've done that (except archive decompression bacause of source code is downloaded uncompressed - but I think it doesn't matter), but error `No such module ‘UseDesk_SDK_Swift’` still occurs.

**Comment by nichvolod** [comment]
One more advice than :) 

Paste this snippet to the end of the podfile

> post_install do |pi|
  pi.pods_project.targets.each do |t|
    t.build_configurations.each do |config|
      config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
    end
  end
end

And run `pod install` once again

**Comment by nichvolod** [comment]
Our pleasure! 
Sure, we will fix this moment :)
