### ISSUE TITLE
Privacy Manifest

### ISSUE THREAD

**Issue by justnicke** [usedesk/UseDeskSwift#22]
Добрый день!

На WWDC 23 Apple представила Privacy Manifest.

Подскажите, когда планируете обновление СДК? [Дедлайн](https://developer.apple.com/news/?id=3d8a9yyh) от Apple до 1 мая 

References:
[Upcoming third-party SDK requirements](https://developer.apple.com/support/third-party-SDK-requirements/)
[Privacy updates for App Store submissions](https://developer.apple.com/news/?id=3d8a9yyh)
[Describing use of required reason API](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api)

Как минимум, есть ошибка SwiftSoup, требуется обновить версию. SwiftSoup манифест добавили
![manifest_error](https://github.com/usedesk/UseDeskSwift/assets/52747028/dd390a65-8979-4a3c-af27-7c3066c1a406)

**Comment by nichvolod** [comment]
Добрый день! 

Мы уже готовимся к релизу, будет доступен в ближайшие пару дней. Напишем сюда тоже :)

**Comment by nichvolod** [comment]
Прошу прощения, с релизом в CocoaPods возникли сложности небольшие, но сегодня до конца дня должно туда доехать тоже. 
Отпишусь

**Comment by nichvolod** [comment]
@justnicke в общем, подсы теперь тоже на месте
