### ISSUE TITLE
Невозможно открыть чат снова в случае если его закрыли через dismiss всех вьюконтроллеров

### ISSUE THREAD

**Issue by 2ndOracle** [usedesk/UseDeskSwift#25]
Так как переменная isOpenSDKUI устанавливается в true при старте, а на false меняется только в функции releaseChat

releaseChat не вызывается если вьюконтроллер чата просто умирает

**Comment by nichvolod** [comment]
@2ndOracle Привет! 
Забрали на обсуждение. Подумаем, что тут можем предложить

**Comment by Mr-Sergey-K** [comment]
@2ndOracle При закрытии контроллера, на котором вызывается SDK, вы можете вызвать метод releaseChat().
