### ISSUE TITLE
Приложение крешится после обновления версии бибиотеки до 1.1.2

### ISSUE THREAD

**Issue by MinakovPavel** [usedesk/UseDeskSwift#6]
Could not load NIB in bundle: 'NSBundle </private/var/folders/n5/cnlg59vj5t5g7g24njl7w8mr0000gn/X/44EB6542-782F-57DE-89ED-141E1491E3A3/d/Wrapper/Sushimaster.app> (loaded)' with name 'UDAttachSmallCameraCollectionViewCell'

**Comment by Mr-Sergey-K** [comment]
Исправлено начиная с версии 1.1.4
